<?php
/** @var $block \Magento\Catalog\Block\Product\View */

$product = $block->getProduct();
$buttonTitle = __('Update Cart');
/** @var \FPX\Connector\Helper\FpxProduct $fpxProductHelper */
$fpxProductHelper = $this->helper('FPX\Connector\Helper\FpxProduct');
?>
<?php if ($product->isSaleable()) : ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <?php if (!$fpxProductHelper->isFpxEnabledByProductId($product->getId())) : ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @noEscape */ echo __('Qty'); ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   value=""
                                   title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                                   class="input-text qty"
                                   data-validate="{'required-number':true,digits:true}"/>
                        </div>
                    </div>
                <?php else : ?>
                    <input type="hidden" name="qty" id="qty" value="1"/>
                <?php endif; ?>
            <?php endif; ?>
            <div class="actions">
                <?php if (!$fpxProductHelper->isFpxEnabledByProductId($product->getId())) : ?>
                    <button type="submit"
                            title="<?php echo $block->escapeHtml($buttonTitle); ?>"
                            class="action primary tocart"
                            id="product-updatecart-button">
                        <span><?php /* @noEscape */ echo $buttonTitle; ?></span>
                    </button>
                <?php endif; ?>
                <?php echo $block->getChildHtml('', true); ?>
            </div>
        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
