<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */

use Magento\Framework\Data\Helper\PostHelper; ?>

<?php
$fpxProductHelper = $this->helper('FPX\Connector\Helper\FpxProduct');

switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = !empty($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist) : ?>

    <?php if ($type == 'related' || $type == 'upsell') : ?>
        <?php if ($type == 'related') : ?>
            <div class="block <?php /* @noEscape */ echo $class; ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?php /* @noEscape */ echo $limit; ?>"
                 data-shuffle="<?php /* @noEscape */ echo $shuffle; ?>">
        <?php else : ?>
            <div class="block <?php /* @noEscape */ echo $class; ?>"
                 data-mage-init='{"upsellProducts":{}}'
                 data-limit="<?php /* @noEscape */ echo $limit; ?>"
                 data-shuffle="<?php /* @noEscape */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else : ?>
        <div class="block <?php /* @noEscape */ echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php /* @noEscape */ echo $class?>-heading" role="heading" aria-level="2">
            <?php /* @noEscape */ echo $title; ?>
        </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php /* @noEscape */ echo $class?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart) : ?>
            <?php foreach ($items as $item) : ?>
                <?php if (!$fpxProductHelper->isFpxEnabledByProductId($item->getId())) { ?>
                    <div class="block-actions">
                        <?php /* @noEscape */ echo __('Check items to add to the cart or') ?>
                        <button type="button" class="action select" role="select-all">
                            <span><?php /* @noEscape */ echo __('select all') ?></span>
                        </button>
                    </div>
                <?php
                    break;
} ?>
            <?php endforeach ?>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?php /* @noEscape */ echo $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php $itemsCount = count($items); ?>
                <?php foreach ($items as $item) : ?>
                <?php $available = ''; ?>
                <?php if (!$item->isComposite() && $item->isSaleable() && $type == 'related') : ?>
                    <?php if (!$item->getRequiredOptions()) : ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell') : ?>
                    <?php /* @noEscape */ echo($iterator++ == 1)
                            ? '<li class="item product product-item" style="display: none;">'
                            : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else : ?>
                    <?php /* @noEscape */ echo($iterator++ == 1)
                            ? '<li class="item product product-item">'
                            : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?php /* @noEscape */ echo $available; ?>">
                    <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
                    <a href="<?php /* @noEscape */ echo $block->getProductUrl($item) ?>"
                       class="product photo product-item-photo">
                        <?php echo $block->getImage($item, $image)->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link" title="<?php echo $block->escapeHtml($item->getName()) ?>"
                               href="<?php /* @noEscape */ echo $block->getProductUrl($item) ?>">
                                <?php echo $block->escapeHtml($item->getName()) ?>
                            </a>
                        </strong>

                        <?php /* @noEscape */ echo $block->getProductPrice($item); ?>

                            <?php if ($templateType) : ?>
                                <?php echo $block->getReviewsSummaryHtml($item, $templateType) ?>
                            <?php endif; ?>

                            <?php if (!$item->isComposite() && $item->isSaleable() && $type == 'related'
                                && !$fpxProductHelper->isFpxEnabledByProductId($item->getId())) : ?>
                                <?php if (!$item->getRequiredOptions()) : ?>
                                    <div class="field choice related">
                                        <input type="checkbox"
                                               class="checkbox related"
                                               id="related-checkbox<?php /* @noEscape */ echo $item->getId() ?>"
                                               name="related_products[]"
                                               value="<?php /* @noEscape */ echo $item->getId() ?>" />
                                        <label class="label"
                                               for="related-checkbox<?php /* @noEscape */ echo $item->getId() ?>">
                                            <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                        </label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart) : ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart) : ?>
                                        <div class="actions-primary">
                                            <?php if ($item->isSaleable()) : ?>
                                                <?php $itemId = $item->getId(); ?>
                                                <?php if (!$fpxProductHelper->isFpxEnabledByProductId($itemId)) : ?>
                                                    <?php if ($item->getTypeInstance()->hasRequiredOptions($item)) : ?>
                                                        <?php $cartUrl = $block->getAddToCartUrl($item); ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{
                                                                    "redirectUrl": {
                                                                        "url": "<?php /* @noEscape */ echo $cartUrl; ?>"
                                                                    }
                                                                }'
                                                                type="button"
                                                                title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else : ?>
                                                        <?php
                                                        $postDataHelper = $this->helper(PostHelper::class);
                                                        $postData = $postDataHelper->getPostData(
                                                            $block->getAddToCartUrl($item),
                                                            ['product' => $item->getEntityId()]
                                                        )
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @noEscape */ echo $postData; ?>'
                                                                type="button"
                                                                title="<?php /* @noEscape */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <?php if ($item->getIsSalable()) : ?>
                                                    <div class="stock available">
                                                        <span><?php /* @noEscape */ echo __('In stock') ?></span>
                                                    </div>
                                                <?php else : ?>
                                                    <div class="stock unavailable">
                                                        <span><?php /* @noEscape */ echo __('Out of stock') ?></span>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo) : ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                <?php echo $addToBlock->setProduct($item)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == $itemsCount+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
<?php endif;?>
