<?php
use Magento\Framework\App\Action\Action;

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$fpxProductHelper = $this->helper('FPX\Connector\Helper\FpxProduct');
?>
<?php if (!$_productCollection->getSize()) : ?>
    <div class="message info empty">
        <div><?php /* @noEscape */ echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $wrapperClass = 'products wrapper ' . $viewMode . ' products-' . $viewMode;
    ?>
    <div class="<?php /* @noEscape */ echo $wrapperClass; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php $collectionCount = count($_productCollection); ?>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php /* @noEscape */ echo($iterator++ == 1)
                    ? '<li class="item product product-item">'
                    : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>">
                                <?php /* @noEscape */ echo $_helper->productAttribute(
                                    $_product,
                                    $_product->getName(),
                                    'name'
                                ); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @noEscape */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"
                                <?php /* @noEscape */ echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"
                                    <?php /* @noEscape */ echo strpos($pos, $viewMode . '-primary')
                                        ? $position
                                        : ''; ?>>
                                    <?php if ($_product->isSaleable()) : ?>
                                        <?php if ($fpxProductHelper->isFpxEnabledByProductId($_product->getId())) : ?>
                                            <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                                               class="action tocart primary">
                                                <span><?php /* @noEscape */ echo __('View'); ?></span>
                                            </a>
                                        <?php else : ?>
                                            <?php
                                            $postParams = $block->getAddToCartPostParams($_product);
                                            $dataProduct = $postParams['data']['product'];
                                            $uenc = [
                                                'name' => Action::PARAM_NAME_URL_ENCODED,
                                                'value' => $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                            ];
                                            ?>
                                            <form data-role="tocart-form"
                                                  action="<?php /* @noEscape */ echo $postParams['action']; ?>"
                                                  method="post">
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?php /* @noEscape */ echo $dataProduct; ?>">
                                                <input type="hidden"
                                                       name="<?php /* @noEscape */ echo $uenc['name']; ?>"
                                                       value="<?php /* @noEscape */ echo $uenc['value']; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php endif; ?>
                                    <?php else : ?>
                                        <?php if ($_product->getIsSalable()) : ?>
                                            <div class="stock available">
                                                <span><?php /* @noEscape */ echo __('In stock') ?></span>
                                            </div>
                                        <?php else : ?>
                                            <div class="stock unavailable">
                                                <span><?php /* @noEscape */ echo __('Out of stock') ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"
                                    <?php /* @noEscape */ echo strpos($pos, $viewMode . '-secondary')
                                        ? $position
                                        : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription) :?>
                                <div class="product description product-item-description">
                                    <?php /* @noEscape */ echo $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?php /* @noEscape */ echo $_product->getProductUrl() ?>"
                                       title="<?php /* @noEscape */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @noEscape */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == $collectionCount+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
