<?php
/** @var $block \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart */
/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
$fpxProductHelper = $this->helper('FPX\Connector\Helper\FpxProduct');
?>
<?php if (!$fpxProductHelper->isFpxEnabledByProductId($product->getId())) : ?>
    <?php foreach ($block->getChildNames() as $childName) : ?>
        <?php /* @noEscape */ echo $block->getLayout()->renderElement($childName, false); ?>
    <?php endforeach;?>
    <div class="box-tocart">
        <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()) : ?>
            <div class="field qty">
                <label class="label" for="qty[<?php /* @noEscape */ echo $item->getId() ?>]">
                    <span><?php /* @noEscape */ echo __('Qty') ?></span>
                </label>
                <div class="control">
                    <input type="number"
                           data-role="qty"
                           id="qty[<?php /* @noEscape */ echo $item->getId() ?>]"
                           class="input-text qty"
                           data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                           name="qty[<?php /* @noEscape */ echo $item->getId() ?>]"
                           value="<?php /* @noEscape */ echo $block->getAddToCartQty($item) * 1 ?>">
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable()) : ?>
        <div class="product-item-actions">
            <div class="actions-primary">
                <button type="button"
                        data-role="tocart"
                        data-post='<?php /* @noEscape */ echo $block->getItemAddToCartParams($item)?>'
                        title="<?php /* @noEscape */ echo __('Add to Cart') ?>"
                        data-item-id="<?php /* @noEscape */ echo $item->getId()?>"
                        class="action tocart primary">
                    <span><?php /* @noEscape */ echo __('Add to Cart') ?></span>
                </button>
            </div>
        </div>
        <?php else : ?>
            <?php if ($product->getIsSalable()) : ?>
                <p class="available stock" title="<?php /* @noEscape */ echo __('Availability') ?>">
                    <span><?php /* @noEscape */ echo __('In stock') ?></span>
                </p>
            <?php else : ?>
                <p class="unavailable stock" title="<?php /* @noEscape */ echo __('Availability') ?>">
                    <span><?php /* @noEscape */ echo __('Out of stock') ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
        </fieldset>
    </div>
<?php endif; ?>
