<?php
/**
 * Last ordered items sidebar
 *
 * @var $block \Magento\Sales\Block\Reorder\Sidebar
 */
?>
<div class="block block-reorder" data-bind="scope: 'lastOrderedItems'">
    <div class="block-title no-display"
         data-bind="css: {'no-display': !lastOrderedItems().items || lastOrderedItems().items.length === 0}">
        <strong id="block-reorder-heading" role="heading" aria-level="2">
            <?php /* @noEscape */ echo __('Recently Ordered') ?>
        </strong>
    </div>
    <div class="block-content no-display"
         data-bind="css: {'no-display': !lastOrderedItems().items || lastOrderedItems().items.length === 0}"
         aria-labelledby="block-reorder-heading">
    </div>
    <strong class="subtitle"><?php /* @noEscape */ echo __('Last Ordered Items') ?></strong>
    <ol id="cart-sidebar-reorder" class="product-items product-items-names"
        data-bind="foreach: lastOrderedItems().items">
        <li class="product-item">
            <a data-bind="attr: {href: url}" class="product-item-link" target="_blank">
                <span data-bind="text: name"></span>
            </a>
        </li>
    </ol>
    <div id="cart-sidebar-reorder-advice-container"></div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "lastOrderedItems": {
                    "component": "Magento_Sales/js/view/last-ordered-items"
                }
            }
        }
    }
}
</script>
